#!/usr/bin/env python3
"""Generate the metadata indexes under .docs/generated/ from page front matter.

Writes objects/domains/tags/relationships/related JSON plus Explore pages.
Refuses to run if the validator reports errors. Output is deterministic
(sorted keys, sorted lists, LF, trailing newline), so a second run is a no-op.

Usage: python3 .docs/tools/generate_index.py [--root PATH]
"""
import argparse
import json
import math
import os
import re
import shutil
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import validate  # noqa: E402
from common import (DupKeyLoader, list_pages, load_taxonomy_full, read_text,  # noqa: E402
                    split_front_matter, submodule_paths)

WORDS_PER_MIN = 200
QUICK_MIN = 10          # "quick read" threshold, in minutes
LEVEL_RANK = {"beginner": 0, "intermediate": 1, "advanced": 2}
FENCE_RE = re.compile(r"^(```|~~~).*?^\1[^\n]*$", re.DOTALL | re.MULTILINE)
OUT_REL = ".docs/generated"
EXPLORE = "explore"
HEADER = "<!-- Generated by .docs/tools/generate_index.py. Do not edit. -->\n"


def write(root, rel, content):
    path = os.path.join(root, OUT_REL, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def dump(obj):
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def esc(text):
    return text.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]").replace("|", "\\|")


def reading_time_min(body):
    """Whole minutes at 200 wpm over the page body, fenced code excluded, minimum 1."""
    words = len(FENCE_RE.sub(" ", body).split())
    return max(1, math.ceil(words / WORDS_PER_MIN))


def load_objects(root):
    objects = {}
    subs = set(submodule_paths(root))
    for path in list_pages(root, subs):
        text = read_text(root, path)
        split = split_front_matter(text)
        if split is None:
            continue
        data = yaml.load(split[0], Loader=DupKeyLoader) or {}
        if "id" not in data:
            continue  # indexed pages need an explicit id; the validator guards relations
        rel = data.get("relations") or {}
        objects[data["id"]] = {
            "id": data["id"],
            "path": path,
            "title": data["title"],
            "summary": (data.get("summary") or "").strip(),
            "level": data.get("level") or "",
            "reading_time_min": reading_time_min(text[split[1]:]),
            "type": data["type"],
            "status": data["status"],
            "domains": sorted(data["domains"]),
            "tags": sorted(data.get("tags") or []),
            "relations": {
                "prerequisites": sorted(rel.get("prerequisites") or []),
                "related": sorted(rel.get("related") or []),
            },
        }
    return objects


def build_relationships(objects):
    rels = {oid: {"prerequisites": [], "prerequisite_of": [], "related": [], "related_by": []}
            for oid in objects}
    for oid, obj in objects.items():
        for t in obj["relations"]["prerequisites"]:
            rels[oid]["prerequisites"].append(t)
            rels[t]["prerequisite_of"].append(oid)
        for t in obj["relations"]["related"]:
            rels[oid]["related"].append(t)
            rels[t]["related_by"].append(oid)
    for r in rels.values():
        for k in r:
            r[k] = sorted(set(r[k]))
    return rels


def build_related(objects, rels):
    """Per page path: the data behind the 'Related' block rendered at deploy time."""
    def ref(i):
        return {"id": i, "path": objects[i]["path"], "title": objects[i]["title"]}

    out = {}
    for oid, obj in objects.items():
        r = rels[oid]
        shown = set(r["prerequisites"]) | set(r["prerequisite_of"])
        both = sorted((set(r["related"]) | set(r["related_by"])) - shown, key=lambda i: (objects[i]["title"].lower(), i))
        block = {
            "prerequisites": [ref(i) for i in sorted(r["prerequisites"], key=lambda i: (objects[i]["title"].lower(), i))],
            "required_by": [ref(i) for i in sorted(r["prerequisite_of"], key=lambda i: (objects[i]["title"].lower(), i))],
            "related": [ref(i) for i in both],
        }
        if any(block.values()):
            out[obj["path"]] = block
    return out


def group(objects, key):
    g = {}
    for oid, obj in objects.items():
        for v in obj[key]:
            g.setdefault(v, []).append(oid)
    return {k: sorted(v) for k, v in g.items()}


def meta_line(o):
    bits = [x for x in (o["level"], f"{o['reading_time_min']} min") if x]
    return " · ".join(bits)


def page_bullet(o):
    line = f"- [{esc(o['title'])}](/{o['path']})"
    if o["summary"]:
        line += f" — {o['summary']}"
    return line + f" *({meta_line(o)})*"


def page_list(objects, ids, tag_link):
    out = []
    for i in sorted(ids, key=lambda i: (objects[i]["title"].lower(), i)):
        o = objects[i]
        out.append(page_bullet(o) + ("  " if o["tags"] else ""))
        if o["tags"]:
            out.append("  " + " ".join(f"[`{t}`]({tag_link(t)})" for t in o["tags"]))
    return "\n".join(out) + "\n"


def learning_paths(objects):
    """Connected chains of prerequisites, each in a valid reading order."""
    adj, indeg = {}, {i: 0 for i in objects}
    for i, o in objects.items():
        for t in o["relations"]["prerequisites"]:
            adj.setdefault(t, []).append(i)
            indeg[i] += 1
    parent = {i: i for i in objects}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    linked = set()
    for t, nxt in adj.items():
        for i in nxt:
            parent[find(i)] = find(t)
            linked |= {t, i}
    comps = {}
    for i in linked:
        comps.setdefault(find(i), []).append(i)

    key = lambda i: (LEVEL_RANK.get(objects[i]["level"], 1), objects[i]["title"].lower(), i)  # noqa: E731
    paths = []
    for members in comps.values():
        deg = {i: indeg[i] for i in members}
        ready = sorted((i for i in members if deg[i] == 0), key=key)
        order = []
        while ready:
            n = ready.pop(0)
            order.append(n)
            for m in adj.get(n, []):
                deg[m] -= 1
                if deg[m] == 0:
                    ready.append(m)
            ready.sort(key=key)
        paths.append(order)
    return sorted(paths, key=lambda p: (objects[p[0]]["title"].lower(), p[0]))


def start_here(objects, tax):
    lines = [HEADER, "# Start here\n",
             "Pick a cup: follow a path, grab a quick read, or start with the basics.\n"]
    paths = learning_paths(objects)
    if paths:
        lines.append("## Learning paths\n")
        lines.append("Read each path in order; every step builds on the one before.\n")
        for order in paths:
            counts = {}
            for i in order:
                for d in objects[i]["domains"]:
                    counts[d] = counts.get(d, 0) + 1
            top = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]
            total = sum(objects[i]["reading_time_min"] for i in order)
            lines.append(f"### {tax['domains'][top]['label']} · {len(order)} steps · {total} min\n")
            for n, i in enumerate(order, 1):
                o = objects[i]
                line = f"{n}. [{esc(o['title'])}](/{o['path']})"
                if o["summary"]:
                    line += f" — {o['summary']}"
                lines.append(line + f" *({meta_line(o)})*")
            lines.append("")
    quick = sorted((i for i, o in objects.items() if o["reading_time_min"] <= QUICK_MIN),
                   key=lambda i: (objects[i]["reading_time_min"], objects[i]["title"].lower(), i))
    if quick:
        lines += [f"## Quick reads ({QUICK_MIN} minutes or less)\n"]
        lines += [page_bullet(objects[i]) for i in quick] + [""]
    beginner = sorted((i for i, o in objects.items() if o["level"] == "beginner"),
                      key=lambda i: (objects[i]["title"].lower(), i))
    if beginner:
        lines += ["## Beginner friendly\n"]
        lines += [page_bullet(objects[i]) for i in beginner] + [""]
    return "\n".join(lines).rstrip("\n") + "\n"


def explore_url(kind, key):
    return f"/{OUT_REL}/{EXPLORE}/{kind}/{key}.md"


def generate(root):
    root = os.path.abspath(root)
    tax = load_taxonomy_full(root)
    objects = load_objects(root)
    rels = build_relationships(objects)
    by_domain, by_tag = group(objects, "domains"), group(objects, "tags")

    out = os.path.join(root, OUT_REL)
    if os.path.isdir(out):
        shutil.rmtree(out)

    write(root, "objects.json", dump(objects))
    write(root, "relationships.json", dump(rels))
    write(root, "related.json", dump(build_related(objects, rels)))
    write(root, "domains.json", dump({
        d: {"label": meta["label"], "description": meta.get("description", ""),
            "objects": by_domain.get(d, [])}
        for d, meta in tax["domains"].items()}))
    write(root, "tags.json", dump({
        t: {"label": meta["label"], "objects": by_tag.get(t, [])}
        for t, meta in tax["tags"].items()}))

    tag_link = lambda t: explore_url("tags", t)  # noqa: E731

    write(root, f"{EXPLORE}/start-here.md", start_here(objects, tax))

    # Domains
    lines = [HEADER, "# Domains\n", "Pages grouped by subject. Folders stay the primary location; "
             "this is an overlay.\n"]
    for d, meta in sorted(tax["domains"].items()):
        ids = by_domain.get(d)
        if not ids:
            continue
        lines.append(f"- [{meta['label']}]({explore_url('domains', d)}) ({len(ids)})"
                     + (f": {meta['description']}" if meta.get("description") else ""))
        write(root, f"{EXPLORE}/domains/{d}.md",
              f"{HEADER}\n# {meta['label']}\n\n{meta.get('description', '')}\n\n"
              + page_list(objects, ids, tag_link)
              + f"\n[All domains]({'/' + OUT_REL}/{EXPLORE}/domains.md)\n")
    write(root, f"{EXPLORE}/domains.md", "\n".join(lines) + "\n")

    # Tags
    lines = [HEADER, "# Tags\n", "Pages grouped by topic tag.\n"]
    for t, meta in sorted(tax["tags"].items()):
        ids = by_tag.get(t)
        if not ids:
            continue
        lines.append(f"- [{meta['label']}]({explore_url('tags', t)}) ({len(ids)})")
        write(root, f"{EXPLORE}/tags/{t}.md",
              f"{HEADER}\n# {meta['label']}\n\n"
              + page_list(objects, ids, tag_link)
              + f"\n[All tags]({'/' + OUT_REL}/{EXPLORE}/tags.md)\n")
    write(root, f"{EXPLORE}/tags.md", "\n".join(lines) + "\n")

    n_legacy = len(list_pages(root, set(submodule_paths(root)))) - len(objects)
    return objects, n_legacy


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    args = ap.parse_args()
    rep, n_pages, n_fm = validate.run(args.root)
    rep.emit()
    if rep.errors:
        print("not generating: fix validation errors first", file=sys.stderr)
        sys.exit(1)
    objects, n_legacy = generate(args.root)
    print(f"indexed {len(objects)} pages; {n_legacy} legacy pages have no metadata "
          f"(coverage {len(objects)}/{len(objects) + n_legacy})")


if __name__ == "__main__":
    main()
