#!/usr/bin/env python3
"""Generate the metadata indexes under .docs/generated/ from page front matter.

Writes objects/domains/tags/relationships/related JSON plus Explore pages.
Refuses to run if the validator reports errors. Output is deterministic
(sorted keys, sorted lists, LF, trailing newline), so a second run is a no-op.

Usage: python3 .docs/tools/generate_index.py [--root PATH]
"""
import argparse
import json
import os
import shutil
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import validate  # noqa: E402
from common import (DupKeyLoader, list_pages, load_taxonomy_full, read_text,  # noqa: E402
                    split_front_matter, submodule_paths)

OUT_REL = ".docs/generated"
EXPLORE = "explore"
HEADER = "<!-- Generated by .docs/tools/generate_index.py. Do not edit. -->\n"


def write(root, rel, content):
    path = os.path.join(root, OUT_REL, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def dump(obj):
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def esc(text):
    return text.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]").replace("|", "\\|")


def load_objects(root):
    objects = {}
    subs = set(submodule_paths(root))
    for path in list_pages(root, subs):
        split = split_front_matter(read_text(root, path))
        if split is None:
            continue
        data = yaml.load(split[0], Loader=DupKeyLoader) or {}
        if "id" not in data:
            continue  # indexed pages need an explicit id; the validator guards relations
        rel = data.get("relations") or {}
        objects[data["id"]] = {
            "id": data["id"],
            "path": path,
            "title": data["title"],
            "type": data["type"],
            "status": data["status"],
            "domains": sorted(data["domains"]),
            "tags": sorted(data.get("tags") or []),
            "relations": {
                "prerequisites": sorted(rel.get("prerequisites") or []),
                "related": sorted(rel.get("related") or []),
            },
        }
    return objects


def build_relationships(objects):
    rels = {oid: {"prerequisites": [], "prerequisite_of": [], "related": [], "related_by": []}
            for oid in objects}
    for oid, obj in objects.items():
        for t in obj["relations"]["prerequisites"]:
            rels[oid]["prerequisites"].append(t)
            rels[t]["prerequisite_of"].append(oid)
        for t in obj["relations"]["related"]:
            rels[oid]["related"].append(t)
            rels[t]["related_by"].append(oid)
    for r in rels.values():
        for k in r:
            r[k] = sorted(set(r[k]))
    return rels


def build_related(objects, rels):
    """Per page path: the data behind the 'Related' block rendered at deploy time."""
    def ref(i):
        return {"id": i, "path": objects[i]["path"], "title": objects[i]["title"]}

    out = {}
    for oid, obj in objects.items():
        r = rels[oid]
        shown = set(r["prerequisites"]) | set(r["prerequisite_of"])
        both = sorted((set(r["related"]) | set(r["related_by"])) - shown, key=lambda i: (objects[i]["title"].lower(), i))
        block = {
            "prerequisites": [ref(i) for i in sorted(r["prerequisites"], key=lambda i: (objects[i]["title"].lower(), i))],
            "required_by": [ref(i) for i in sorted(r["prerequisite_of"], key=lambda i: (objects[i]["title"].lower(), i))],
            "related": [ref(i) for i in both],
        }
        if any(block.values()):
            out[obj["path"]] = block
    return out


def group(objects, key):
    g = {}
    for oid, obj in objects.items():
        for v in obj[key]:
            g.setdefault(v, []).append(oid)
    return {k: sorted(v) for k, v in g.items()}


def page_table(objects, ids, tag_link):
    rows = ["| Page | Type | Status | Tags |", "|---|---|---|---|"]
    for i in sorted(ids, key=lambda i: (objects[i]["title"].lower(), i)):
        o = objects[i]
        tags = ", ".join(f"[{t}]({tag_link(t)})" for t in o["tags"])
        rows.append(f"| [{esc(o['title'])}](/{o['path']}) | {o['type']} | {o['status']} | {tags} |")
    return "\n".join(rows) + "\n"


def explore_url(kind, key):
    return f"/{OUT_REL}/{EXPLORE}/{kind}/{key}.md"


def generate(root):
    root = os.path.abspath(root)
    tax = load_taxonomy_full(root)
    objects = load_objects(root)
    rels = build_relationships(objects)
    by_domain, by_tag = group(objects, "domains"), group(objects, "tags")

    out = os.path.join(root, OUT_REL)
    if os.path.isdir(out):
        shutil.rmtree(out)

    write(root, "objects.json", dump(objects))
    write(root, "relationships.json", dump(rels))
    write(root, "related.json", dump(build_related(objects, rels)))
    write(root, "domains.json", dump({
        d: {"label": meta["label"], "description": meta.get("description", ""),
            "objects": by_domain.get(d, [])}
        for d, meta in tax["domains"].items()}))
    write(root, "tags.json", dump({
        t: {"label": meta["label"], "objects": by_tag.get(t, [])}
        for t, meta in tax["tags"].items()}))

    tag_link = lambda t: explore_url("tags", t)  # noqa: E731

    # Domains
    lines = [HEADER, "# Domains\n", "Pages grouped by subject. Folders stay the primary location; "
             "this is an overlay.\n"]
    for d, meta in sorted(tax["domains"].items()):
        ids = by_domain.get(d)
        if not ids:
            continue
        lines.append(f"- [{meta['label']}]({explore_url('domains', d)}) ({len(ids)})"
                     + (f": {meta['description']}" if meta.get("description") else ""))
        write(root, f"{EXPLORE}/domains/{d}.md",
              f"{HEADER}\n# {meta['label']}\n\n{meta.get('description', '')}\n\n"
              + page_table(objects, ids, tag_link)
              + f"\n[All domains]({'/' + OUT_REL}/{EXPLORE}/domains.md)\n")
    write(root, f"{EXPLORE}/domains.md", "\n".join(lines) + "\n")

    # Tags
    lines = [HEADER, "# Tags\n", "Pages grouped by topic tag.\n"]
    for t, meta in sorted(tax["tags"].items()):
        ids = by_tag.get(t)
        if not ids:
            continue
        lines.append(f"- [{meta['label']}]({explore_url('tags', t)}) ({len(ids)})")
        write(root, f"{EXPLORE}/tags/{t}.md",
              f"{HEADER}\n# {meta['label']}\n\n"
              + page_table(objects, ids, tag_link)
              + f"\n[All tags]({'/' + OUT_REL}/{EXPLORE}/tags.md)\n")
    write(root, f"{EXPLORE}/tags.md", "\n".join(lines) + "\n")

    n_legacy = len(list_pages(root, set(submodule_paths(root)))) - len(objects)
    return objects, n_legacy


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    args = ap.parse_args()
    rep, n_pages, n_fm = validate.run(args.root)
    rep.emit()
    if rep.errors:
        print("not generating: fix validation errors first", file=sys.stderr)
        sys.exit(1)
    objects, n_legacy = generate(args.root)
    print(f"indexed {len(objects)} pages; {n_legacy} legacy pages have no metadata "
          f"(coverage {len(objects)}/{len(objects) + n_legacy})")


if __name__ == "__main__":
    main()
